---
title: "Tarea2"
author: "Juan Carlos D赤az Flores         c.u:000132965"
date: "24 de agosto de 2014"
output: html_document
---
```{r}
## Pregunta 1
 library(datasets)
 data(iris)
 ?iris
 iris
## Mediante la funci車n library cargamos el paquete datasets, con data llamamos a el conjunto de datos iris que es un data.frame, que corresponde a la medida y especies de ciertas plantas.
```

```{r}
## Pregunta 2
 str(iris)
## Se puede ver que tiene 5 variables y 150 observaciones
 class(iris[[1]])
 class(iris[[2]])
 class(iris[[3]])
 class(iris[[4]])
 class(iris[[5]])
## De igual manera con la funci車n sapply
 sapply(iris, class)
```

```{r}
## Pregunta 3
 sum(is.na(iris))
## El numero total de valores faltantes es 0 
```

```{r}
## Pregunta 4
## La suma de las columnas
 colSums(iris[,-5])
## El promedio de las columnas
 colMeans(iris[,-5])
```

```{r}
## Pregunta 5
 ?sapply
 ?sum
 ?mean
## Verificando
 sapply(iris[,-5], sum)
 sapply(iris[,-5], mean)
```

```{r}
## Pregunta 6
## Los renglones que cumplen con dicha condici車n
 which(iris[1]>=5.84)
```

```{r}
## Pregunta 7
## El n迆mero de renglones que cumplen con la condici車n
 colSums(iris[1]>=5.84)
## La suma de los renglones que cumplen con la condici車n
 sum(iris[1][iris[1]>=5.84])
## El promedio de los renglones que cumplen con la condici車n
 mean(iris[1][iris[1]>=5.84])
```

```{r}
## Pregunta 8
 ?subset
## Los datos que cumplen con las condiciones
 subset(iris, Species == "setosa" & iris[1]>5.4, select=Sepal.Length)
## Las observaciones que cumplen con las condiciones son
 which((iris[1]>5.4) & iris[5]=="setosa")
```

```{r}
## Pregunta 9
## Incluimos la especie virginica dadas las condiciones de la pregunta anterior
 subset(iris, (Species %in% c("virginica","setosa")) & iris[1]>5.4, select=Sepal.Length)
```

```{r}
## Pregunta 10
## El c車digo que guarda un archivo con las condiciones es
 write.table(tail(iris),file = "UltimasObs.csv", sep = ",", row.names = FALSE)
```

```{r}
## Pregunta 11
 cuadratica  <- function(a,b,c){
   if(((b^2)-4*a*c)>0){
     x1 <- (-b+sqrt((b^2)-4*a*c))/(2*a)
     x2 <- (-b-sqrt((b^2)-4*a*c))/(2*a)
     return(c(x1,x2))
   } else if(((b^2)-4*a*c)==0){
     x1 <- (-b/(2*a))
     x2 <- (-b/(2*a))
     return(c(x1,x2))
   } else
     print("No existe solucion en los reales")
 }
## En este ejercicio tuve un problema ya que yo queria escribir la palabra soluci車n con acento, el problema es que cuando le agrego el acento me aparece una combinaci車n rara, creo que es por poner el acento en el c車digo, y ya intete cambiar a UTF-8 pero como utilizo mac no me sirvio.

## Ejemplos
 cuadratica(a = 3, b = -1 , c = -2)
 cuadratica(a = 9, b = 12, c = 4)
 cuadratica(a = 1, b = 1, c = 1)
```

```{r}
## Pregunta 12
 anualidad <- function(n,i,P=1,Vencida=TRUE){
   s <- 0
   for(j in 1:n){
     x1 <- ((1/(1+i))^j)
     s <- x1+s
   }
   x2 <- P*s
   round(x2,3)
   if(Vencida==TRUE){
     return(x2)
   } else{
     x3 <- x2*(1+i)
     return(x3)
   }
 }
## Ejemplos
 anualidad(n = 15, i = 0.035)
 anualidad(n = 15, i = 0.035, P = 5000)
 anualidad(n = 15, i = 0.035, P = 5000, Vencida = FALSE)
## Cuando aplico estas funciones en la consola si me da los valores con decimales, pero cuando corro en HTML lo redondea  
```
